### PR TITLE
Elasticsearch compatibility

### PR DESCRIPTION
**Pull request by triat**
Hello,

Here is my first PR about elasticsearch integration (#69). 

It seems to work on my laptop, I didn't did much and there is certainly still a lot of improvement but as I said, I never worked with ES before so it's pretty hard for me to know what and how. 

If people want to try it there is already something that should work.

Also if you don't set up anything, it will still goes to the database as it does right now.

### CODE REVIEW

**Comment by triat** [comment]
@avelis Hey, can you double check this test ? I'm pretty sure it's totally wrong and let only slow api pass ....
`    @flaky
    def test_log_time_fast(self):
        self.client.get('/logging')
        log = APIRequestLog.objects.first()
    
        # response time is very short
        self.assertLessEqual(log.response_ms, 20)
    
        # request_at is time of request, not response
>       self.assertGreaterEqual((now() - log.requested_at).total_seconds(), 0.002)
E       AssertionError: 0.00186 not greater than or equal to 0.002`

**Comment by avelis** [comment]
@triat That test specifically has been in place since before I took over the project. Just something I haven't gotten around to fixing. I can also remove the reference to Python 3.3. Looks like it's not supported anymore.

**Comment by avelis** [comment]
@triat TravisCI reported an issue with OSS public Linux builds. Not sure if it has been resolved.

**Comment by avelis** [comment]
@triat Looks pretty fubar'd here. Not sure what is going on. Gonna have to email support.
https://travis-ci.org/aschn/drf-tracking/builds/280615567

**Comment by avelis** [comment]
@triat I finally found my answer. It looks like the build matrix the limit of 200 and needs to be reduced in order for it to continue.

https://travis-ci.org/aschn/drf-tracking/requests

**Comment by triat** [comment]
Awesome! Anyway, my thing is not working like I want. I still have to work on it :)

**Comment by triat** [comment]
Actually, I'll close this one as the override of the `handle_log` solve this issue. Everyone can now log to what he wants

**Pull request closed without merging**
