### PR TITLE
Support for Django 2.0 and Python 3.6

### PR DESCRIPTION
**Pull request by rafen**
Hi, I found that the main issues were:

 * deprecation of `MIDDLEWARE_CLASSES` setting variable in Django 2.0
 * `is_anonymous` now is a property, not a function
 * conversions from `bytes` to `unicode` from requests responses.
 
I also reconfigured the tests config files to be able to run tests on Travis for Python 3.6 and Django 2.0.
Here the results: https://travis-ci.org/rafen/drf-tracking/builds/346883235
But I dropped test support for Python 2.7, Django < 2.0 and DRF < 3.7

So please feel free to use this PR o close it and use it as a reference for changes.

Thanks for the all the good work of this repo 👍

### CODE REVIEW

**Comment by triat** [comment]
Hey, I wanted to know, you had to drop old tests because of the incompatibility? 

Even if I like the idea of moving on, I'm not sure we can drop those tests like that. I mean there is still people using py2.7 and django<2.0

**Comment by rafen** [comment]
I drop the tests because I'm short on time and some of them were failing, maybe something simple to fix.
If I have more time I will try to push another PR.

**Comment by josefkorbel** [comment]
Okay, this PR is from February, now we have October, any news regarding this? @triat

**Comment by triat** [comment]
@josefkorbel I actually did a PR recently, which was merged and I've updated as much as I could to be compatible with Django 1.11 / 2.0 / 2.1. I guess it should work fine. Maybe you can try to pull it from master until @avelis create a new version.

Let me know if there is something not working as expected

**Comment by josefkorbel** [comment]
@triat Awesome, good work. I actually have to wait for proper pypi release as I am using this inside a docker container and I dont want to mess with SSH inside it. Will try from source as soon as I will have some free time, just to confirm it is working.

**Comment by triat** [comment]
you know that you can also install it from the source with `-e git+https://github.com/aschn/drf-tracking@master#egg=drf-tracking` and you can even put this line in your requirements file, it will be taken in account like if it was a pypi. So you won't have to mess with your SSH and docker ;)

**Comment by avelis** [comment]
I apologize for not creating a new release. Been recently stretched thin way too thin to help. But I want to get another release out as soon as possible.

**Comment by triat** [comment]
Is this PR bringing something knew on master now ? I'm not sure if we should keep it or not

**Pull request closed without merging**
