### PR TITLE
Don't consume streaming response content

### PR DESCRIPTION
**Pull request by rib3**
Check for streaming response, if so do not consume content

### CODE REVIEW

**Comment by rib3** [comment]
CI failure due to flake8 failure

fix submitted separately as: #138

**Comment by rib3** [comment]
rebased now that #138 has been merged

**Comment by rib3** [comment]
@avelis

Is this a good time to cut 1.5.1 and publish to pypi?
#132 contains another fix that was merged after 1.5.0.  (Looks like a few people have commented about it via #134)

**Comment by avelis** [comment]
@rib3 Good idea. Busy today will look into it soon.

**Pull request merged**
