### PR TITLE
Fix #23 - handle log without TransactionManagementError

### LINKED ISSUE #23: Transactions breaking on creation if logging.
I am getting an error with logging on write operations. 

The DB is PostgreSQL 9.5 and using latest Django Rest Framework.

> TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

Has anyone else run into this issue. I didn't notice anything in the issues.

### PR DESCRIPTION
**Pull request by itcrab**
Hello! I got this error today: https://github.com/aschn/drf-tracking/issues/23.

How to reproduce?

1. View:
```Python
from rest_framework import generics
from rest_framework.response import Response
from rest_framework_tracking.mixins import LoggingMixin

class LoggingView(LoggingMixin, generics.GenericAPIView):
    logging_methods = ['GET']

    def get(self, request):
        return Response('with logging')
```
2. Enable any DRF authorization (I using tokens).
3. Open API endpoint without token or get 404 for any another API endpoint (with logging)

Thats all - when I open API endpoint I have no store any logs in database.
And I have no any error messages from system...

This works that because we have `try ... catch` statement: https://github.com/aschn/drf-tracking/blob/master/rest_framework_tracking/mixins.py#L66

My PR have the fix this error using simple way.

I hope you may fast see this PR and merging it. Thank's!

P.S. I think another fix https://github.com/aschn/drf-tracking/pull/48 is not good decision.

### CODE REVIEW

**Comment by itcrab** [comment]
One moment - I added test for this case (try reproduce in test).

**Comment by itcrab** [comment]
Add tests don't needed - when we enable ATOMIC_REQUESTS:
https://github.com/aschn/drf-tracking/pull/104/files#diff-484462fced51d1a06b1d93b4a44dd535R51

We  got some exists error-tests in master branch (commit: `ea19d364208e75df3b3667504231cc56f52636b0`).

My last commit `2fada98f4cdc44bf66043f18047aaa2205efb974` in this PR fix this problem - all tests passed!

**Comment by itcrab** [comment]
In current PR I also fixed another error-tests from master branch - please see it.

**Comment by avelis** [comment]
@itcrab Thanks for addressing issue #28 and contributing to this library.

**Pull request merged**
