### PR TITLE
ES compatibility 

### PR DESCRIPTION
**Pull request by triat**
Finally a new PR to implement #69 which seems to work properly on our production.

Some explanation of my PR:

- I added parameter to remove exception as you might not want an external library to logs error in your system
- I added a parameter to allow you to remove the data from the request you send to ES, I didn't wanted to have a function to clean it as I was afraid it might slow down the API response. Also depending which data you send back, you might reach the limit of index of ES really quick (in case you have a different key each time you answer like a uuid key)
- there is not other test as I didn't saw the needs for it. Most of the code didn't changed and I simply added a small if which send the data to ES.

If you have some concern on the PR or what it does with ES, please correct me. I'm really new to ES and I'm not sure everything I do is correct for bigger / other ES than mine

## Things that I will do before I merge the PR
- [x] Modify to use the default index if none is provided
- [x] Modify to allow to use personal type

### CODE REVIEW

**Comment by triat** [comment]
@avelis I wonder if because I canceled the old one, you cannot find this one or it's not triggered in travisCI

**Comment by avelis** [comment]
@triat Well, I realized that I was looking at the wrong repo in TravisCI. My bad. Also, the project stopped building 3 months ago because the build matrix is too large. I have to tackle that at some point.

**Comment by avelis** [comment]
@triat Finally made the issue that highlights the other problem. https://github.com/aschn/drf-tracking/issues/97

**Comment by triat** [comment]
Just to let people know, it's been more than a month that my branch is in prod on `python 3.5.4` and `django 1.11` and we don't see any issue related to that.

If you migrate from DB to ES, just make sure you roll over your indexes and clean them after some time to not kill your cluster.

I'll try to rework it and make possible that we merge it somehow in the master branch

**Comment by triat** [comment]
Thanks @legshort, It has been running in our production for quite a long time now (since feb so ~8 months) and not much to say except it works :)

Now, starting to get a bit of experience with DRF and API in general, I'd say that this is not the best way to track your API. When you discuss about API, you want it to be quick, really quick and having a tool in the middle, adding load time to the whole process request, is not perfect. 

About my ES integration, I can share it, I don't think it adds a lot of load on the request (what takes a lot of time is mostly the code that you run behind the API as the answer of an ES is normally super fast).

To that I see at least 2 better ways to do it:
- Async logging to ES from DRF-tracking, like that you reduce the load to almost 0
- DRF-tracking using the logger, as it is already used by Django, you wouldn't add more load to the request than it is already taking right now (or almost none), and you could configure your logger the way you want (like for example, having your handler logging to a different file that you parse with FileBeat -> Logstash -> ES)

Anyway, I'll try to rebase this PR on the master and push it again so you could review it if you think it is useful (the changes are actually pretty simple)

**Comment by legshort** [comment]
@triat thanks for sharing your thoughts and I think your concerns can be resolved with this community.
I'm looking forward to seeing your PR.

Also, I think sending data to ES wouldn't bother that much and I concern about sync if async logging task fails for any reason.
Plus it requires a little work such as celery setup and redis and stuff.

**Comment by triat** [comment]
@legshort here you are, you should have the latest content of my branch.

@avelis Could you re-trigger the bot to validate the branch ? I have the feeling it is still stuck :)

**Pull request closed without merging**
