### PR TITLE
feat(): logging should never break the API

### PR DESCRIPTION
**Pull request by gbataille**
I had the case that while being attacked, the attacker changed the x-forwarded-for header with a non-ip in there. The logging db insert fails on the inet field.

No issue while logging should actually block the API behind.

I would like to put a giant try/except around the entire code actually BUT a comment on line 65 disturbs me (where the request data actually saved in `request.log`).

### CODE REVIEW

**Comment by avelis** [comment]
Your expectation of a library not interfering with the API underneath is absolutely fair.

Once the tests pass I can merge it in. This PR could use one a unit teat to assert this expectation though.

**Comment by gbataille** [comment]
yeah I know :)
I'm busy fixing our other internal prod code! but I'll try to come back to
it later

**Comment by gbataille** [comment]
ok, I put a test and actually added some more issue handling, not trying to access `request.log` in the finalize if it does not exist (whatever failed in the `initialize` method)

**Comment by avelis** [comment]
@gbataille First, I want to say thanks for writing a unit test. I reviewed it and have a request change about importing mock.

**Comment by gbataille** [comment]
I added mock in the requirements.txt file. the problem is that it's not in
the same place in python 2 and python 3, thus the try/except dance.

Are the requirements installed in the CI?
I could make it work with both python 2 and python 3 locally

**Comment by avelis** [comment]
@gbataille It would appear that that TravisCI does install from the requirements.txt file.

**Comment by gbataille** [comment]
It does in the preparation of TOX (i.e. in the python 3.5 tox execution env)
```
$ pip --version
adding /home/travis/.cache/pip to cache
pip 9.0.1 from /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages (python 3.5)
install.1
$ pip install -r requirements.txt
```

but after that, I don't seem to see any trace that tox installs them in the test runner python 2.7 environment.
Actually this might be that tox test deps should be defined in the tox.ini.
Let me try that.

**Comment by avelis** [comment]
@gbataille You should be able to run tox locally by installing tox via pip and just running `$ tox`command in the same directory as the tox.ini file. We can see if your latest change will work with TravisCI. Unfortunately, I just kicked of a build on a merge for another PR. The builds take a while. Might want to check back later.

**Comment by avelis** [comment]
@gbataille Thanks again for you diligent effort in this PR.

**Pull request merged**
