### PR TITLE
Feat/strings

### PR DESCRIPTION
**Pull request by jameshiew**
Set a `verbose_name` for both the app itself and the `BaseAPIRequestLog` model, makes things look a bit neater in the admin

Also a suggestion for a default `__str__` method

### CODE REVIEW

**Comment by avelis** [comment]
@jameshiew Restarting TravisCI build. Only one test failed but it's odd why it did.

**Comment by jameshiew** [comment]
`test_log_time_fast` sometimes fails, I've marked it as flaky to see if Travis will pass

**Comment by avelis** [comment]
@jameshiew I completely forgot that flaky exists. However, there seems to be a module import error with flaky.

**Comment by avelis** [comment]
@jameshiewThanks for the contribution and for making the previous PR which made this possible to merge.

**Pull request merged**
