### PR TITLE
Small Refactor

### PR DESCRIPTION
**Pull request by tselepakis**
I realized that some parts could be written a bit better.

### CODE REVIEW

**Comment by tselepakis** [comment]
@avelis that was fast :+1:

**Comment by avelis** [comment]
@tselepakis Thanks again for the refactor! I appreciate the effort. I really need to make a release soon. :-)

**Comment by avelis** [comment]
@tselepakis If possible, could you update the README docs on how to use the class mixin constants?

**Comment by tselepakis** [comment]
@avelis no problem but I would like your insight on that. This pr does not introduce anything new, at least user wised. The constants are meant to be used for development purposes, in order this to be more clear we could move them outside of the class.

On the other hand, we could make them available to the users. The user will be able to define his `CLEANED_SUBSTITUTE` (something that is not possible for now) and set his `SENSITIVE_FIELDS` (something that is partially supported now, you can only extend the predefined set of sensitive fields).

In that case, `CLEANED_SUBSTITUTE` and `SENSITIVE_FIELDS` are not going to be so constant.

There is also [sensitive_fields](https://github.com/aschn/drf-tracking/blob/master/rest_framework_tracking/mixins.py#L12) which let you extend `SENSITIVE_FIELDS`. If we go with that option the it would be better to drop the extend functionality (breaking change).

Thoughts?

**Comment by triat** [comment]
Regarding the 'CLEANED_SUBSTITUTE' I didn't gave the possibility to the user to change it because it doesn't really matter I think, the point here is to change the value to not have it in the DB without encoding.

About the 'SENSITIVE_FIELDS' the point was to let the user extend it but not remove it (security issue appears if you do it). 

I don't mind about the 'CLEANED_SUBSTITUTE' if you prefer to have '+++' instead of '*****' but I would keep the way 'SENSITIVE_FIELDS' works right now.

**Pull request merged**
