### PR TITLE
Django 2.0 compatibility

### PR DESCRIPTION
**Pull request by webbyfox**

### CODE REVIEW

**Comment by avelis** [comment]
@webbyfox Thanks for making a PR. For thoroughness sake have you ran tests locally to see if it presents any failures?

**Comment by gvr4wd** [comment]
it should be user.is_authenticated not user.is_autenticated in the code.

**Comment by avelis** [comment]
@webbyfox Sorry for the late reply. Can you correct the typo @gvr4wd mentioned?

**Comment by avelis** [comment]
@webbyfox This was fixed in #110 
Closing this PR. Thanks for contributing the fix either way.

**Pull request closed without merging**
