### PR TITLE
Add name of the view to the log

### PR DESCRIPTION
**Pull request by triat**
Hey,

A bit of explanation behind this PR.

So we're using drf-tracking for our API but we found a problem when we wanted to use the data to draw some graphs. Actually logging the path is pretty annoying because you can have non static information like an ID, key, or other user related informations.

That's why I've tried to log the view itself, as we have all the other information (method / user_id) we can know exactly for what was the API call.

I'm not sure this is the best way to do it, it is working as far as I tested for my API and I'm looking forward for your comments / suggestions.

### CODE REVIEW

**Comment by avelis** [comment]
@triat thanks for making this PR! If you can write a unit test on this additional field that would be greatly appreciated. I can merge it in after.

**Comment by triat** [comment]
Hey, sure I will do it tomorrow if it's alright for you. Sorry, that I didn't before

**Comment by avelis** [comment]
@triat No worries.

**Comment by triat** [comment]
@avelis So I did a bit of refactoring (the previous way was a bit weird to retrieve the name of the view with the actions and ... anyway) and wrote few tests. 

If you have other cases that you want me to check, let me know

**Comment by triat** [comment]
@avelis Before you merge, I just noticed that when you have a viewset, you don't know the action of your class so I'm changing again a bit how it works, it will be done tonight or tomorrow morning

**Comment by avelis** [comment]
@triat Sounds good. Thanks for writing the tests for the PR.

**Comment by triat** [comment]
@avelis sure no problem

**Comment by triat** [comment]
Hey @avelis, do you need something more on this PR or are you checking things ?

**Comment by avelis** [comment]
@triat Thanks for the contribution!

With all the coverage comments I was missed your last commits and merge

**Comment by triat** [comment]
@avelis can I ask you if you planned to do a release (build of pip package) in the next few days / weeks? To know if I can put my production on the pip package or if I have to stay on the git branch.

Thanks

**Comment by avelis** [comment]
@triat You can totally ask. I will get one out by EOW

**Pull request merged**
