### PR TITLE
Update mixins.py

### PR DESCRIPTION
**Pull request by null-none**
Condition for the integration of different responses.

Example:

from django.http import HttpResponse
...
...
return HttpResponse(serializer.get_result(), content_type='text/plain; charset=utf8')

### CODE REVIEW

**Comment by null-none** [comment]
Condition for the integration of different responses.

Example:

from django.http import HttpResponse
...
...
return HttpResponse(serializer.get_result(), content_type='text/plain; charset=utf8')

**Comment by null-none** [comment]
Improve condition

**Comment by avelis** [comment]
@null-none I have no issue merging this in However, is there a parent method that we can call on the `HttpResponse` class that could handle returning the correct intended value in a polymorphic way?

**Comment by null-none** [comment]
@avelis He's harmless. But people will be able to use your mixin without the DFR.

**Pull request merged**
