### PR TITLE
Restructured regex to handle underscores as suffix/prefix for sensitive data.

### PR DESCRIPTION
**Pull request by bkovacev**
https://github.com/aschn/drf-tracking/issues/56

### CODE REVIEW

**Comment by avelis** [comment]
@bkovacev I like the effort thus far. Is it possible to add some unit tests for this change? Also, is this a breaking regex change? Will the old words still work or are underscore suffix(es) & prefix(es) required now?

**Comment by bkovacev** [comment]
Glad to hear that. I'll definitely add more tests in a bit.

I assume this would be a breaking change 😞 Of the old words only password remains the same, others do require the prefix. Check the issue I've submitted, the old regex would catch 'api' in 'capitalization_cost' and 'key' in 'keyless_entry' .

**Comment by avelis** [comment]
@bkovacev If there is an improvement here then I accept a breaking change on that merit :-). I was asking for versioning purposes is all.

**Comment by bkovacev** [comment]
@avelis Added couple of tests and refactored one as well! 👍

**Comment by bkovacev** [comment]
Hmm it seems my tests are failing because the response content while the same is in a slightly different ordering. Can you take a look?

**Comment by avelis** [comment]
@bkovacev Can you use `self.assertDictEquals` I believe this checks the dictionary keys and values are the same does not necessarily care about order.

**Comment by avelis** [comment]
@bkovacev I am having trouble accessing your PR because your forked and PR's on a branch called master. However, looking at you changes it looks like one is expecting `capitalization-cost` but is seeing`capitalization_cost` or vice verse. Either way one is an underscore the other is a hyphen.

As for the key value pair ordering. I would likely tell you to teach to the test to match the storing. Since, Django converts the dict to a text column via Django's TextField serialization process. I don't know the exact process of serialization without looking into Django's source. You could change the key value order in the `str()` to pass the test or to try to match the dict to string serialization that Django's TextField performs.

**Comment by bkovacev** [comment]
So should I create a new pull request on a different branch?

**Comment by avelis** [comment]
@bkovacev It still looks like there is an serialization order issue that is causing certain tests to fail. It's only for some of test configurations in the test matrix. Since query_params is stored as a string You could either try to json load the string as a dict and compare dicts or emulate Django's str serialization for the query_params column.

**Comment by triat** [comment]
Hey, I agree that the regex catch maybe too much but I don't agree with the way we do it.

I see the point with API, but secret, key, token etc are word that can be there alone. 

What I mean is that the list and the way it is done right now is taken from django. It's a bit more specific for them but I'd prefer to be more safe than less. 

If we want to do that, we should either be able to set our own list of "words" or change only API

**Comment by bkovacev** [comment]
@triat Take a look at the issue #56 

'capitalized_cost' (my field)
'keyless_entry'
'user_signature_jpg_url'
'secret_ingredient' (can't think of any other word at the moment, but I'm sure there might be couple of others)

These are all the words that get caught by api, key and signature regex. If you just remove the API it won't solve the other cases. 

I do not think that it's a good practice to force users to model their data so that this library can support it.

However, I do like the idea of us providing a list of field which values we would not liked logged.

**Comment by triat** [comment]
Sure but in your case, you doesn't care about words that might be secret and which should be hidden.

I'm working on a fix because I'm actually thinking that this changes breaks everything in prod (I mean, my changes). I'm not sure if `self.request` is a copy of the request or not, if not, we do have an issue which is: we modify the payload, and that's not good

**Comment by bkovacev** [comment]
First of, this would be solved by versioning, since this is a pull request it may or may not be included in the next big version bump. Second, we do modify the payload anyway since you clean the data[key] :) 

You wouldn't need to do any of that, for the global list to work. The function takes on a regex, it wouldn't need much to be adjusted to accept a list.

Current clean_data function:
```
def _clean_data(data):
    """
    Clean a dictionary of data of potentially sensitive info before
    sending to the database.
    Function based on the "_clean_credentials" function of django
    (django/django/contrib/auth/__init__.py)
    """
    SENSITIVE_DATA = re.compile('(_api)|(api_)|(_token)|(token_)|(_key)|(key_)|(_secret)|(secret_)|(_password)|'
                                '(password_)|(password)|(_signature)|(signature_)', re.I)
    CLEANSED_SUBSTITUTE = '********************'
    for key in data:
        if SENSITIVE_DATA.search(key):
            data[key] = CLEANSED_SUBSTITUTE
```

Possible clean_data function:
`settings.py`
`DRF_TRACKING_EXCLUDE = ['api', 'your_field', 'another_field']`

```
from django.conf import settings

def _clean_data(data):
    """
    Clean a dictionary of data of potentially sensitive info before
    sending to the database.
    Function based on the "_clean_credentials" function of django
    (django/django/contrib/auth/__init__.py)
    """
    SENSITIVE_DATA = settings.DRF_TRACKING_EXCLUDE
    CLEANSED_SUBSTITUTE = '********************'
    
    # Make it more readable via list comprehension
    for key in data:
        for item in SENSITIVE_DATA:
            if key==item:
                data[key] = CLEANSED_SUBSTITUTE
```

@avelis

**Comment by triat** [comment]
That's exactly what I mean, I do change the payload and it breaks things! I mean, we remove a password from the payload, which means, you cannot log in anymore.

And yes, it's not a lot of work to have a settings for the list

**Comment by bkovacev** [comment]
@triat From my understanding, you modify the payload sent to the actual DRF-TRACKING view, but you don't modify the actual payload you're sending to your ie login endpoint.

**Comment by triat** [comment]
@bkovacev so my point is just to make sure that we do not remove real values with this thing.

**Comment by avelis** [comment]
First off. Great discussion. I really appreciate the attention to detail and execution here.

My thoughts on a potential solution is to move away from the regex search and instead use a Python `list` or `set`. I also like the idea of an extendable or overridable setting of sensitive words to clean if found. This allows for **a)** whole word matching and **b)** customizable data cleaning depending on your usage.

The code snippet @bkovacev provided above is a great start here. One challenge I see will be case insensitive matching. This is what regex pattern search gives you almost for free. However, the pro's of extendability and not using regex I think is still worthwhile.
 
@bkovacev @triat Thoughts concerns?

@triat In regards to drf-tracking not modifying the request data, I think PR #63 is looking into addressing that issue specifically.

**Comment by triat** [comment]
@avelis yes the PR from Greg is trying to fix that but it's not totally correct, I'm going to update it and make it more correct (directly update it in the clean data function)

About the list of words, I think we should keep a regex that match exactly the word in an insensitive way.

One proposition for the regex replacement could be that:

`
DRF_TRACKING_EXCLUDE = ['api', 'token', 'key', 'secret', 'password', 'signature']

def _clean_data(data):
    """
    Clean a dictionary of data of potentially sensitive info before
    sending to the database.
    Function based on the "_clean_credentials" function of django
    (django/django/contrib/auth/__init__.py)
    """
    reg = ''
    for word in DRF_TRACKING_EXCLUDE:
        reg += '($' + word + '^)|'
    SENSITIVE_DATA = re.compile(reg[:-1], re.I)
    CLEANSED_SUBSTITUTE = '********************'
    for key in data:
        if SENSITIVE_DATA.search(key):
            data[key] = CLEANSED_SUBSTITUTE
    return data
`
In this case we keep the regex and we force the exact word

**Comment by bkovacev** [comment]
These are just _**my personal**_ thoughts regarding the regex and the list issue in the clean_data func.

* I think that **explicit** is better than implicit. (while regex is technically explicit, it still becomes implicit when 'capitalizated_cost' gets caught, which is not something I as a user would want).

  * Give the user some freedom to determine what he wants to hide. 

* Coming from the usability endpoint, I don't want a library to dictate my naming convention.

* I would either want to have a "exclude_logging_fields" in my APIView and a global list of fields.
  * Global list of fields might handle any fields within a library/mixin you can't/don't want to modify.
  * And a specific list of exclude_logging_fields, maybe you want to obfuscate some other fields within the model, like Social Security Number, Passport Number etc.
  * This in my opinion nails it.

* Or would I want to be able to construct my regex.

**Comment by triat** [comment]
@bkovacev I see your point. I though it would be better to avoid to set "Key", "KEY", "key". It is maybe just a matter of preferences. 

Freedom is good, but I still think that security is good too and some keyword should be hidden by default (password especially)

**Comment by avelis** [comment]
@bkovacev I am on board with your suggestions with a `sensitive_fields` view setting.

One of the challenges that `_clean_data` has that Django's `_clean_credentials` does not have is control of the keys Django wants to clean. This is likely why Django opted for a regex. The key set is finite and controlled. `_clean_data` does not have that luxury but is still useful in providing security benefits.

@triat One way to get around case sensitivity issue is to force the case using `.lower()` or `.upper()`. That could be used on all the keys in the sensitive fields list used in `_clean_data` as well as the keys passed into `_clean_data` as an argument.

If you anyone here amends/updates this PR or another new one with the collaborated suggestions I can take a look and merge it in.

**Comment by triat** [comment]
@avelis @bkovacev I'll give it a try, unfortunately I can't modify this PR, so I'll do an other one

**Comment by avelis** [comment]
@bkovacev @triat I am going to close this PR. I believe the work merged into master addressed this PR in spirit.

**Pull request closed without merging**
